# Site settings
title: "KITCTF"
baseurl: ""
url: "https://kitctf.de"
description: "We are a group of students, computer security enthusiasts and CTF players mostly from the Karlsruhe Institute of Technology. If you are interested in hacking with us, write us at team@kitctf.de or come to our weekly meetings. We meet every Thursday at 7 pm in the computer science building (50.34), room -120."

github: kitctf
twitter: KITCTF
mastodon: "https://infosec.exchange/@KITCTF"

# Build settings
markdown: kramdown
permalink: /:categories/:title
plugins:
  - jekyll-redirect-from
include: ["_*.pdf"] # Also copy such pdfs

# Authors
authors:
  saelo:
    url: https://twitter.com/5aelo
  eboda:
    url: https://twitter.com/edgarboda
  niklasb:
    url: https://github.com/niklasb
  mawalu:
    url: https://martinwagner.co
  Liam:
    url: https://wachter-space.de
  intrigus:
    url: https://intrigus.org
  rad4day:
    url: https://tobiasmanske.de
  ik0ri4n:
    url: https://ik0ri4n.de/
  Ik0ri4n:
    url: https://ik0ri4n.de/

teamname: KITCTF
